_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("maps.urls")),
]

maps/urls.py
from django.urls import path

from . import views
from . import api

app_name = "maps"

urlpatterns = [
    path("", views.MapView.as_view(), name="map"),
    path("api/locations/", api.LocationListAPIView.as_view(), name="api-location-list"),
]

maps/models.py
from django.db import models


class Location(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    latitude = models.CharField(max_length=10)
    longitude = models.CharField(max_length=10)
    opening_hours = models.JSONField()
    google_maps_url = models.URLField()
    waze_url = models.URLField()

    def __str__(self):
        return self.name


class Distance(models.Model):
    origin = models.ForeignKey(
        Location, on_delete=models.CASCADE, related_name="origin"
    )
    destination = models.ForeignKey(
        Location, on_delete=models.CASCADE, related_name="destination"
    )
    distance = models.FloatField(help_text="Distance in km")

    def __str__(self):
        return f"{self.origin} - {self.destination}"

    # Unique together origin and destination
    class Meta:
        unique_together = ("origin", "destination")

maps/views.py
from django.views.generic import ListView
from .models import Location


class MapView(ListView):
    model = Location
    template_name = "maps/map.html"

maps/templates/maps/_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
              crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
                crossorigin="anonymous"></script>
        {% block head %}
        {% endblock head %}
    </head>
    <body data-bs-theme="dark">
        <nav class="navbar navbar-expand-lg border-bottom" style="background-color:#303134">
            <div class="container-fluid">
                <a class="navbar-brand fw-semibold" href="#">Maps</a>
            </div>
        </nav>
        <div class="container-fluid mt-4">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

<style>
    body {
        font-size: 0.9rem;
    }
</style>

maps/templates/maps/map.html
{% extends "maps/_base.html" %}
{% block title %}
    Maps
{% endblock title %}
{% block head %}
    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
            integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
            crossorigin=""></script>
{% endblock head %}
{% block content %}
    {# Search bar #}
    <div class="mb-4 d-flex gap-2">
        <input id="searchInput"
               type="text"
               class="form-control form-control-lg"
               placeholder="Search for something...">
    </div>
    {# Main content #}
    <div class="row g-2" style="height: 75vh;">
        {# Location list #}
        <div class="col-lg-4 d-flex flex-column order-2 order-lg-1"
             style="height: 100%">
            <div id="locationContainer"
                 class="list-group list-group-numbered overflow-auto flex-grow-1">
                {# Dynamic content will be loaded here #}
            </div>
            <div id="loadingIndicator" class="mx-2" style="display:none;">
                Loading...
                <div class="spinner-border spinner-border-sm" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </div>
            <div id="errorIndicator" class="mx-2" style="display:none;">Error loading data. Please try again.</div>
            <div id="emptyIndicator" class="mx-2" style="display:none;">
                No results found.
                <a href="#" onclick="fetchData()">Reload.</a>
            </div>
            <div id="locationDataInfoDiv" class="mx-2 mt-3" style="display:none;">
                <span id="locationDataInfoValue"></span>.
                <a href="#" onclick="fetchData()">Reload</a>
            </div>
        </div>
        {# Map and widgets #}
        <div class="col-lg-8 d-flex flex-column order-1 order-lg-2">
            <div id="map" class="bg-secondary flex-grow-1"></div>
            <div id="mapWidgets" class="mt-2 d-flex gap-4 small">
                {# Show catchment radius toggle #}
                <div class="d-flex gap-2 align-items-center">
                    <div class="form-check form-switch mt-2">
                        <label for="catchmentRadiusSwitch" class="form-label mb-0 text-nowrap">Show catchment radius (5 km)</label>
                        <input class="form-check-input"
                               type="checkbox"
                               role="switch"
                               id="catchmentRadiusSwitch"
                               checked>
                    </div>
                </div>
                {# Legend 1 #}
                <div class="d-flex gap-2 align-items-center">
                    <img src="https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-blue.png"
                         alt=""
                         height="24px;">
                    <span>Has location within catchment radius</span>
                </div>
                {# Legend 2 #}
                <div class="d-flex gap-2 align-items-center">
                    <img src="https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-green.png"
                         alt=""
                         height="24px;">
                    <span>No location within catchment radius</span>
                </div>
            </div>
        </div>
    </div>
    <script>
        var map = L.map('map', {
            attributionControl: false,
            layers: [
                L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png')
            ]
        }).setView(
            [3.1319, 101.6841], 13 // Defaults to somewhere in Kuala Lumpur
        );
    </script>
    <script>
        const loadingIndicator = document.getElementById('loadingIndicator');
        const errorIndicator = document.getElementById('errorIndicator');
        const locationContainer = document.getElementById('locationContainer');
        const emptyIndicator = document.getElementById('emptyIndicator');
        const locationDataInfoDiv = document.getElementById('locationDataInfoDiv');
        const locationDataInfoValue = document.getElementById('locationDataInfoValue');
        let info = '';
        const idToMarkerMap = {}; // Object to store id-marker associations
        
        // Fetch data from the server for both the map and the location list
        function fetchData() {
            loadingIndicator.style.display = 'block';
            errorIndicator.style.display = 'none';
            locationContainer.style.display = 'none';
            emptyIndicator.style.display = 'none';
            locationDataInfoDiv.style.display = 'none';
            
            searchValue = document.getElementById('searchInput').value;

            rangeValue = 5; // Default catchment radius
        
            fetch('{% url "maps:api-location-list" %}?range=' + rangeValue + '&general_search=' + searchValue)
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    info = response.headers.get('info');
                    return response.json().then(data => ({ data, info }));
                })
                .then(({ data, info }) => {
                    renderData(data, info);
                })
                .catch(error => {
                    loadingIndicator.style.display = 'none';
                    errorIndicator.style.display = 'block';
                    console.error('There has been a problem with your fetch operation:', error);
                });
        }

        function handleCatchmentRadius(latitude, longitude) {
            // Clear existing catchment radius
            map.eachLayer(function (layer) {
                if (layer instanceof L.Circle) {
                    map.removeLayer(layer);
                }
            });

            if (document.getElementById('catchmentRadiusSwitch').checked) {
                // Add catchment radius
                L.circle([latitude, longitude], {
                    color: 'blue',
                    fillColor: '#007bff',
                    fillOpacity: 0.2,
                    weight: 0.5,
                    radius: rangeValue * 1000
                }).addTo(map);
            }
        }

        function toggleEmptyState() {
            emptyIndicator.style.display = 'block';
            loadingIndicator.style.display = 'none';
            locationContainer.style.display = 'none';
            locationDataInfoDiv.style.display = 'none';
        }

        function toggleDataExistsState() {
            loadingIndicator.style.display = 'none';
            locationContainer.style.display = 'block';
            locationDataInfoDiv.style.display = 'block';
        }

                
        function renderData(data, info) {
            locationContainer.innerHTML = ''; // Clear previous content

            // Clear existing markers and catchment radius
            if (window.locationMarkers) {
                window.locationMarkers.forEach(marker => map.removeLayer(marker));
                map.eachLayer(function (layer) {
                    if (layer instanceof L.Circle) {
                        map.removeLayer(layer);
                    }
                });
            }
            window.locationMarkers = [];
        
            // Check if data is empty and update the container immediately
            if (data.length === 0) {
                toggleEmptyState();
                return;
            } else {
                data.forEach(object => { // Construct new content
                    const locationElement = document.createElement('a');
                    locationElement.href = '#';
                    locationElement.className = 'list-group-item list-group-item-action d-flex justify-content-between align-items-start';
                    locationElement.dataset.id = object.id;
                    locationElement.dataset.latitude = object.latitude;
                    locationElement.dataset.longitude = object.longitude;
                    locationElement.innerHTML = `
                        <div class="ms-2 me-auto">
                            <h6 class="text-light">${object.name}</h6>
                            <span class="d-block mb-2">${object.address}</span>
                            <ul class="mb-1">
                                ${object.opening_hours.map(hrs => `<li>${hrs}</li>`).join('')}
                            </ul>
                        </div>
                    `;
                    locationContainer.appendChild(locationElement);

                    if (object.has_nearby_locations === true) {
                        var markerIcon = new L.Icon({
                            iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-blue.png',
                            shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
                            iconSize: [25, 41],
                            iconAnchor: [12, 41],
                            popupAnchor: [1, -34],
                            shadowSize: [41, 41]
                        });
                    } else {
                        var markerIcon = new L.Icon({
                            iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-green.png',
                            shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
                            iconSize: [25, 41],
                            iconAnchor: [12, 41],
                            popupAnchor: [1, -34],
                            shadowSize: [41, 41]
                        });
                    }

                    // Create a marker and add it to the map
                    const marker = L.marker(
                        [object.latitude, object.longitude],
                        {icon: markerIcon},
                    ).addTo(map);
                    const popupContent = `
                        <b>${object.name}</b>
                        <p class="my-1">${object.address}</p>
                        <ul class="mb-2">
                            ${object.opening_hours.map(hrs => `<li>${hrs}</li>`).join('')}
                        </ul>
                        <div class="collapse" id="nearbyLocationsCollapse${object.id}">
                            Nearby locations:
                            <ol class="mb-1">
                                ${object.nearby_locations.map(loc => `<li>${loc}</li>`).join('')}
                            </ol>
                        </div>
                        <a href="#" data-bs-toggle="collapse" data-bs-target="#nearbyLocationsCollapse${object.id}" aria-expanded="false" aria-controls="nearbyLocationsCollapse${object.id}">
                            Show nearby locations (${object.nearby_locations.length})
                        </a>
                    `;
                    marker.bindPopup(popupContent);
                    idToMarkerMap[object.id] = marker;
                    window.locationMarkers.push(marker);

                    // When marker is clicked, execute handleCatchmentRadius
                    marker.on('click', function() {
                        handleCatchmentRadius(object.latitude, object.longitude);
                    });

                });
                locationDataInfoValue.innerText = info;
            }
            toggleDataExistsState();
        }

        // listen to locationContainer click event
        locationContainer.addEventListener('click', function(event) {
            let locationItem = event.target.closest('.list-group-item');;
            if (!locationItem) return; // Exit if no list-group-item was clicked

            const { id, latitude, longitude } = locationItem.dataset;
            const marker = idToMarkerMap[id];
            
            marker.openPopup();
            map.panTo(new L.LatLng(latitude, longitude));

            handleCatchmentRadius(latitude, longitude);
        });

        // listen to catchmentRadiusSwitch change event
        document.getElementById('catchmentRadiusSwitch').addEventListener('change', function() {
            if (!this.checked) {
                map.eachLayer(function (layer) {
                    if (layer instanceof L.Circle) {
                        map.removeLayer(layer);
                    }
                });
            }
        });

        // When the search input changes, and then idle for 500ms, execute fetchData
        let searchTimeout = null;
        document.getElementById('searchInput').addEventListener('input', function() {
            clearTimeout(searchTimeout);
            searchTimeout = setTimeout(fetchData, 500);
        });
        
        // Initial fetch when page loads
        fetchData();
        

    </script>
{% endblock content %}